# Generated by Django 5.1.7 on 2025-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedresponse',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('ro', 'Romanian'), ('eng', 'English')], max_length=10),
        ),
    ]
